/**
 * Exponential ElGamal decryption over BabyJubJub, for the publisher.
 *
 * This is the ONLY component in the system that holds the committee secret, and the only
 * one that can turn a ciphertext into a number. Everything else -- the contract, the
 * sequencer, every user -- sees points.
 *
 * It is a deliberate re-implementation of `circuits/scripts/lib/elgamal.mjs` rather than an
 * import: that file is ESM JavaScript inside the circuits workspace, and reaching across
 * package boundaries for a security-critical primitive is worse than duplicating ~40 lines.
 * The duplication is only safe because `test/elgamal.test.ts` proves this implementation
 * agrees with the reference one on its own recorded fixtures, including the ciphertext that
 * came out of a real `bet_encrypted` proof.
 */
import { buildBabyjub } from "circomlibjs";

/** Order of the prime-order subgroup generated by Base8. */
export const SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

export type Point = [bigint, bigint];

export interface Decryptor {
  /** Recover m from (C1, C2), searching [0, bound]. Throws if m is outside it. */
  decrypt(c1: Point, c2: Point, bound: bigint): bigint;
}

/**
 * @param secret the committee private key. NEVER log this, and never log a value derived
 *               from it other than the ratio the publisher is allowed to emit.
 */
export async function buildDecryptor(secret: bigint): Promise<Decryptor> {
  if (secret <= 0n || secret >= SUBGROUP_ORDER) {
    // A secret outside the subgroup silently decrypts to garbage rather than failing, so
    // this is checked rather than assumed.
    throw new Error("committee secret is outside [1, SUBGROUP_ORDER)");
  }

  const babyJub = await buildBabyjub();
  const F = babyJub.F;

  /** The twisted-Edwards identity is (0, 1), not a point at infinity. */
  const IDENTITY = [F.e(0n), F.e(1n)];
  /** On a twisted Edwards curve, -(x, y) = (-x, y). */
  const negate = (p: any) => [F.neg(p[0]), p[1]];
  const key = (p: any) => `${F.toObject(p[0])},${F.toObject(p[1])}`;
  const same = (a: any, b: any) => F.eq(a[0], b[0]) && F.eq(a[1], b[1]);
  const lift = (p: Point) => [F.e(p[0]), F.e(p[1])];

  /**
   * [m]G = C2 - [s]C1, then discrete log by baby-step giant-step.
   *
   * BSGS is why plaintexts must be range-bounded: it is O(sqrt(bound)). A pool total
   * capped at 2^40 costs ~2^20 steps, which is fine. An unbounded plaintext would be
   * unrecoverable, which is why the circuits range-check `units` to AMOUNT_BITS.
   */
  function decrypt(c1: Point, c2: Point, bound: bigint): bigint {
    const target = babyJub.addPoint(lift(c2), negate(babyJub.mulPointEscalar(lift(c1), secret)));
    if (same(target, IDENTITY)) return 0n;

    const m = BigInt(Math.ceil(Math.sqrt(Number(bound))) + 1);

    // Baby steps: a table of [j]G for j in [0, m).
    const table = new Map<string, bigint>();
    let acc: any = IDENTITY;
    for (let j = 0n; j < m; j++) {
      table.set(key(acc), j);
      acc = babyJub.addPoint(acc, babyJub.Base8);
    }

    // Giant steps: walk target back by [m]G until a baby step matches.
    const negMG = negate(babyJub.mulPointEscalar(babyJub.Base8, m));
    let cur: any = target;
    for (let i = 0n; i <= m; i++) {
      const hit = table.get(key(cur));
      if (hit !== undefined) return i * m + hit;
      cur = babyJub.addPoint(cur, negMG);
    }
    throw new Error("BSGS failed -- plaintext outside the searched bound");
  }

  return { decrypt };
}
