// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Deploy} from "../script/Deploy.s.sol";
import {ShieldedPool, IActionVerifier, IEncryptedTotals} from "../src/ShieldedPool.sol";
import {Vault} from "../src/Vault.sol";
import {EncryptedParimutuelPool} from "../src/EncryptedParimutuelPool.sol";

/// @notice The deployment script's END STATE, asserted rather than eyeballed.
///
/// @dev `Deploy.s.sol` had no test. Its correctness was checked by reading the console output
///      of a simulation, which proves nothing about the resulting configuration and re-proves
///      nothing when the script changes.
///
///      The property that matters here is the enforced half of the plaintext deprecation: the
///      script registers the one legacy market the recorded fixtures need and then calls
///      `freezeLegacyMarkets()` in the same transaction, so a deployed instance can never
///      acquire a second one. A legacy market has no redemption path -- the public `redeem()`
///      was removed, and `redeemPrivate` reads settled totals from `EncryptedParimutuelPool`,
///      which a plaintext market does not have -- so collateral deposited into one is stuck.
///      A future operator adding another would strand real funds.
contract DeployConfigTest is Test {
    // anvil account 0 -- a well-known test key, never used for anything real.
    uint256 constant TEST_PK = 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d;

    uint32 constant MARKET_ID = 7;
    uint32 constant ENCRYPTED_MARKET_ID = 8;

    Deploy internal script;
    Deploy.Deployed internal d;
    ShieldedPool internal pool;

    function setUp() public {
        vm.setEnv("PRIVATE_KEY", vm.toString(bytes32(TEST_PK)));
        script = new Deploy();
        d = script.run();
        pool = ShieldedPool(d.pool);
    }

    /// @notice The script leaves legacy market creation permanently shut.
    function test_deploy_freezesLegacyMarkets() public view {
        assertTrue(pool.legacyMarketsFrozen(), "deployment did not freeze legacy markets");
    }

    /// @notice And the freeze is not cosmetic: the admin themselves cannot add another.
    function test_deploy_adminCannotRegisterAnotherPlaintextMarket() public {
        address admin = vm.addr(TEST_PK);
        vm.prank(admin);
        vm.expectRevert(ShieldedPool.LegacyMarketsAreFrozen.selector);
        pool.registerMarket(99, Vault(d.vault));
    }

    /// @notice The freeze must NOT block the market type the product actually uses, or the
    ///         deployment would be inert. This is the half that is easy to break by widening
    ///         the freeze check to cover both registration paths.
    function test_deploy_encryptedMarketsStillRegistrable() public {
        address admin = vm.addr(TEST_PK);
        vm.prank(admin);
        pool.registerEncryptedMarket(99, Vault(d.encryptedVault));
        assertTrue(pool.encryptedMarket(99), "encrypted registration was blocked by the freeze");
    }

    /// @notice Both fixture markets exist, and with the right modes -- the freeze fires AFTER
    ///         registration, not before, or `Exercise.s.sol` would have nothing to replay.
    function test_deploy_bothFixtureMarketsRegistered() public view {
        assertEq(address(pool.marketVault(MARKET_ID)), d.vault, "legacy fixture market missing");
        assertEq(address(pool.marketVault(ENCRYPTED_MARKET_ID)), d.encryptedVault, "encrypted fixture market missing");
        assertFalse(pool.encryptedMarket(MARKET_ID), "legacy market wrongly flagged encrypted");
        assertTrue(pool.encryptedMarket(ENCRYPTED_MARKET_ID), "encrypted market not flagged");
    }

    /// @notice The deployed committee key MATCHES the key the proofs were generated with.
    ///
    /// @dev The first testnet deployment failed here, at settlement, with
    ///      `InvalidDecryptionProof()`. `Deploy.s.sol` hardcoded a committee key copied from
    ///      `circuits/build/committee-key.json`; that file is regenerated by `make keygen`,
    ///      so the copy went stale and the deployed market was bound to a key nobody holds
    ///      the secret for.
    ///
    ///      A market that cannot settle cannot pay out, so this is a fund-stranding bug
    ///      dressed as a constant. It is asserted against the ARTIFACT rather than against
    ///      another constant, because two constants agreeing proves only that they were
    ///      copied together.
    function test_deploy_committeeKeyMatchesTheArtifact() public view {
        string memory json = vm.readFile("../circuits/build/committee-key.json");
        uint256 x = vm.parseJsonUint(json, ".pubKey[0]");
        uint256 y = vm.parseJsonUint(json, ".pubKey[1]");

        EncryptedParimutuelPool enc = EncryptedParimutuelPool(d.encryptedParimutuel);
        assertEq(enc.committeeKeyX(), x, "deployed committee key X is not the one proofs use");
        assertEq(enc.committeeKeyY(), y, "deployed committee key Y is not the one proofs use");
    }

    /// @notice And the key is bound to the pool that settlement actually reads.
    function test_deploy_encryptedTotalsIsTheKeyedPool() public view {
        assertEq(address(pool.encryptedTotals()), d.encryptedParimutuel, "settlement reads an unkeyed pool");
    }

    /// @notice THE EXIT PATH IS WIRED. Without this the pool is a one-way vault.
    ///
    /// @dev The first testnet deployment shipped with all three of these at address(0):
    ///      `Deploy.s.sol` never called `bindEncryptedTotals`. Collateral could be deposited
    ///      and bet, and nothing could ever be paid out -- `redeemPrivate` and `withdraw`
    ///      both revert on a zero verifier, and the public `redeem()` had been removed.
    ///
    ///      The existing tests did not catch it because they asserted what the deployment
    ///      REFUSES (legacy registration) and never what it must ENABLE. This is the missing
    ///      half.
    function test_deploy_exitPathIsWired() public view {
        assertTrue(address(pool.encryptedTotals()) != address(0), "encryptedTotals unbound: nothing can settle");
        assertTrue(address(pool.redeemPrivateVerifier()) != address(0), "redeemPrivateVerifier unbound");
        assertTrue(address(pool.withdrawVerifier()) != address(0), "withdrawVerifier unbound");

        // And bound to the right things, not merely non-zero.
        assertEq(address(pool.encryptedTotals()), d.encryptedParimutuel, "bound to the wrong totals source");
        assertEq(address(pool.redeemPrivateVerifier()), d.redeemPrivateVerifier, "wrong redeem verifier");
        assertEq(address(pool.withdrawVerifier()), d.withdrawVerifier, "wrong withdraw verifier");
    }

    /// @notice Binding is one-shot, so a deployment cannot be silently re-pointed later.
    function test_deploy_bindingIsAlreadyConsumed() public {
        vm.prank(vm.addr(TEST_PK));
        vm.expectRevert(ShieldedPool.AlreadyBound.selector);
        pool.bindEncryptedTotals(
            IEncryptedTotals(d.encryptedParimutuel),
            IActionVerifier(d.redeemPrivateVerifier),
            IActionVerifier(d.withdrawVerifier)
        );
    }

    /// @notice The removed public payout path is gone from the deployed bytecode, not merely
    ///         from the source. Guards against a stale artifact being shipped.
    ///
    /// @dev A scan that finds nothing proves nothing on its own -- a broken scan also finds
    ///      nothing. So the SAME scan is first pointed at `withdraw`, a selector that must be
    ///      present, and required to find it. Only then is a miss on `redeem` meaningful.
    function test_deploy_publicRedeemNotInDeployedCode() public view {
        bytes memory code = address(pool).code;

        bytes4 present =
            bytes4(keccak256("withdraw(uint256[2],uint256[2][2],uint256[2],uint256,uint256,uint256,uint256)"));
        assertTrue(_containsSelector(code, present), "scan is broken: it cannot find a selector that IS present");

        bytes4 removed =
            bytes4(keccak256("redeem(uint256[2],uint256[2][2],uint256[2],uint256,uint256,uint256,uint256)"));
        assertFalse(_containsSelector(code, removed), "removed redeem() selector is still in the deployed bytecode");
    }

    function _containsSelector(bytes memory code, bytes4 sel) internal pure returns (bool) {
        for (uint256 i = 0; i + 4 <= code.length; i++) {
            if (code[i] == sel[0] && code[i + 1] == sel[1] && code[i + 2] == sel[2] && code[i + 3] == sel[3]) {
                return true;
            }
        }
        return false;
    }
}
