// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {IncrementalMerkleTree, IPoseidonT3} from "../src/IncrementalMerkleTree.sol";
import {ActionGasPolicy} from "../src/ActionGasPolicy.sol";

/// @notice PHASE 1 GATE (part 2): does a tree insertion plus a Groth16 verify fit
///         inside the uniform action gas envelope?
///
/// Run with `--network monad`. Both repricings that matter here are confirmed to be
/// applied locally: BN254 precompiles (PrecompileRepricing.t.sol) and the 8,100 cold
/// SLOAD (StorageRepricing.t.sol). Poseidon itself is plain field arithmetic, which
/// Monad does not reprice, and the etched contract's digests were checked against
/// circomlibjs.
contract IncrementalMerkleTreeTest is Test {
    IncrementalMerkleTree tree;
    IPoseidonT3 poseidon;

    /// Measured on live Monad mainnet and testnet -- see MEASUREMENTS.md.
    uint256 constant MEASURED_VERIFY_GAS = 1_029_454;
    uint256 constant MEASURED_POSEIDON2_GAS = 28_980;

    /// Regression ceilings for the figures MEASUREMENTS.md publishes.
    ///
    /// These used to be `console.log` only, which meant the document's numbers could
    /// drift arbitrarily far from the code without anything going red -- the opposite
    /// of PrecompileRepricing.t.sol, which fails loudly. Bounds carry ~10% slack so
    /// solc and forge version noise does not cause churn, while a real regression
    /// (an extra hash per level, a lost batching saving) blows straight through them.
    ///
    /// NOTE the two "unbatched" figures are DIFFERENT code paths, which MEASUREMENTS.md
    /// conflated: `insert()` walks `_insertBatch` and pays all 20 frontier slots cold
    /// (1,107,646), while `insertSubtree([leaf])` grafts at k=0 (691,282). Both are
    /// real; neither is "the" unbatched cost without saying which path.
    uint256 constant MAX_INSERT_SINGLE_GAS = 1_220_000; // measured 1,107,646
    uint256 constant MAX_SUBTREE_N1_GAS = 761_000; // measured   691,282
    uint256 constant MAX_SUBTREE_PER_LEAF_N64 = 42_000; // measured    38,034
    uint256 constant MAX_SEQUENTIAL_PER_LEAF_N64 = 665_000; // measured   604,315
    uint256 constant MAX_NULLIFIER_MAPPING_GAS = 32_000; // measured    28,945
    uint256 constant MAX_NULLIFIER_TREE_GAS = 760_000; // measured   690,733

    /// Grafting must stay overwhelmingly cheaper than the naive loop. Measured 15.9x;
    /// anything below 12x means the batching saving has been broken.
    uint256 constant MIN_GRAFT_REDUCTION_FACTOR = 12;

    /// Keccak of a domain string, reduced into the field. Using a non-zero empty-leaf
    /// value avoids any chance that "empty" and "a real leaf committing to zero"
    /// hash identically.
    uint256 constant ZERO_VALUE = uint256(keccak256("atrum.shielded.empty"))
        % 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function setUp() public {
        // circomlib emits Poseidon as raw EVM assembly, so it is etched rather than
        // compiled. Generated by `circuits/scripts/gen_poseidon.mjs`.
        bytes memory code = vm.parseBytes(vm.trim(vm.readFile("../circuits/build/poseidon2-runtime.hex")));
        address addr = makeAddr("poseidonT3");
        vm.etch(addr, code);
        poseidon = IPoseidonT3(addr);

        tree = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
    }

    // -----------------------------------------------------------------------
    // Correctness first -- a gas number for a broken tree is worthless
    // -----------------------------------------------------------------------

    function test_etchedPoseidonMatchesCircomlibjs() public view {
        // Verified against circomlibjs: poseidon([1,2]).
        assertEq(
            poseidon.poseidon([uint256(1), uint256(2)]),
            0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a,
            "etched Poseidon disagrees with circomlibjs -- on-chain and in-circuit " "hashes would diverge"
        );
    }

    function test_initialRootIsEmptyTreeRoot() public view {
        assertTrue(tree.root() != 0);
        assertEq(tree.nextIndex(), 0);
        assertTrue(tree.isKnownRoot(tree.root()));
    }

    function test_insert_advancesIndexAndChangesRoot() public {
        uint256 before = tree.root();
        tree.insert(uint256(12345));

        assertEq(tree.nextIndex(), 1);
        assertTrue(tree.root() != before, "root did not change");
        assertTrue(tree.isKnownRoot(tree.root()));
        assertTrue(tree.isKnownRoot(before), "previous root fell out of history");
    }

    function test_insert_rejectsNonFieldElement() public {
        vm.expectRevert(IncrementalMerkleTree.LeafNotInField.selector);
        tree.insert(type(uint256).max);
    }

    function test_insertSubtree_rejectsEmpty() public {
        uint256[] memory empty = new uint256[](0);
        vm.expectRevert(IncrementalMerkleTree.EmptyBatch.selector);
        tree.insertSubtree(empty);
    }

    function test_insertSubtree_rejectsNonPowerOfTwo() public {
        uint256[] memory leaves = new uint256[](6);
        vm.expectRevert(IncrementalMerkleTree.BatchNotPowerOfTwo.selector);
        tree.insertSubtree(leaves);
    }

    /// @dev A subtree can only be grafted at its own boundary. Insert 1 leaf, then a
    ///      4-batch would start at index 1, which is not a multiple of 4.
    function test_insertSubtree_rejectsMisaligned() public {
        tree.insert(uint256(1));

        uint256[] memory leaves = new uint256[](4);
        for (uint256 i = 0; i < 4; i++) {
            leaves[i] = 100 + i;
        }
        vm.expectRevert(IncrementalMerkleTree.BatchNotAligned.selector);
        tree.insertSubtree(leaves);
    }

    function test_insertSubtree_rejectsNonFieldElement() public {
        uint256[] memory leaves = new uint256[](2);
        leaves[0] = 1;
        leaves[1] = type(uint256).max;
        vm.expectRevert(IncrementalMerkleTree.LeafNotInField.selector);
        tree.insertSubtree(leaves);
    }

    /// @notice THE correctness property for subtree batching: grafting a bottom-up
    ///         subtree must produce byte-identical state to inserting the same leaves
    ///         one at a time.
    /// @dev Without this, the 17x saving is meaningless -- batching would silently be
    ///      building a different tree, and every Merkle proof generated off-chain
    ///      against the sequential shape would fail on-chain.
    function test_subtreeInsertionMatchesSequentialInsertion() public {
        uint256[4] memory sizes = [uint256(1), 2, 8, 64];

        for (uint256 s = 0; s < sizes.length; s++) {
            uint256 n = sizes[s];

            uint256[] memory leaves = new uint256[](n);
            for (uint256 i = 0; i < n; i++) {
                leaves[i] = 1000 + i;
            }

            IncrementalMerkleTree grafted = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
            grafted.insertSubtree(leaves);

            IncrementalMerkleTree sequential = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
            for (uint256 i = 0; i < n; i++) {
                sequential.insert(leaves[i]);
            }

            assertEq(
                grafted.root(), sequential.root(), "subtree root != sequential root -- batching builds a different tree"
            );
            assertEq(grafted.nextIndex(), sequential.nextIndex());
        }
    }

    /// @notice Consecutive subtree grafts must also match sequential insertion, so
    ///         the frontier is being maintained correctly across batches -- not just
    ///         for the first one starting from an empty tree.
    function test_consecutiveSubtreesMatchSequential() public {
        uint256 n = 8;
        uint256 batches = 3;

        IncrementalMerkleTree grafted = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
        IncrementalMerkleTree sequential = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));

        for (uint256 b = 0; b < batches; b++) {
            uint256[] memory leaves = new uint256[](n);
            for (uint256 i = 0; i < n; i++) {
                leaves[i] = 9000 + b * n + i;
            }

            grafted.insertSubtree(leaves);
            for (uint256 i = 0; i < n; i++) {
                sequential.insert(leaves[i]);
            }

            assertEq(grafted.root(), sequential.root(), "diverged after batch");
        }

        assertEq(grafted.nextIndex(), n * batches);
    }

    function test_isKnownRoot_rejectsUnknownAndZero() public {
        tree.insert(1);
        assertFalse(tree.isKnownRoot(0));
        assertFalse(tree.isKnownRoot(uint256(keccak256("never a root"))));
    }

    // -----------------------------------------------------------------------
    // Access control -- the tree IS the anonymity set
    // -----------------------------------------------------------------------

    function test_insert_revertsForNonSequencer() public {
        vm.prank(makeAddr("outsider"));
        vm.expectRevert(IncrementalMerkleTree.NotSequencer.selector);
        tree.insert(uint256(1));
    }

    function test_insertSubtree_revertsForNonSequencer() public {
        uint256[] memory leaves = new uint256[](2);
        leaves[0] = 1;
        leaves[1] = 2;

        vm.prank(makeAddr("outsider"));
        vm.expectRevert(IncrementalMerkleTree.NotSequencer.selector);
        tree.insertSubtree(leaves);
    }

    function test_insertBatchSequential_revertsForNonSequencer() public {
        uint256[] memory leaves = new uint256[](2);
        leaves[0] = 1;
        leaves[1] = 2;

        vm.prank(makeAddr("outsider"));
        vm.expectRevert(IncrementalMerkleTree.NotSequencer.selector);
        tree.insertBatchSequential(leaves);
    }

    /// @dev An outsider inserting even one leaf between the sequencer's aligned batches
    ///      breaks `insertSubtree`'s alignment rule outright -- the next 64-batch can no
    ///      longer be grafted. This is the concrete damage, not a theoretical one.
    function test_outsiderInsertCannotDesynchroniseBatching() public {
        uint256[] memory batch = new uint256[](64);
        for (uint256 i = 0; i < 64; i++) {
            batch[i] = 9000 + i;
        }
        tree.insertSubtree(batch);

        vm.prank(makeAddr("outsider"));
        vm.expectRevert(IncrementalMerkleTree.NotSequencer.selector);
        tree.insert(uint256(1));

        // Still aligned, so the sequencer's next batch grafts cleanly.
        assertEq(tree.nextIndex(), 64);
        tree.insertSubtree(batch);
        assertEq(tree.nextIndex(), 128);
    }

    function test_constructor_rejectsZeroSequencer() public {
        vm.expectRevert(IncrementalMerkleTree.InvalidSequencer.selector);
        new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(0));
    }

    function test_constructor_rejectsZeroValueOutOfField() public {
        vm.expectRevert(IncrementalMerkleTree.ZeroValueNotInField.selector);
        new IncrementalMerkleTree(
            poseidon, 21888242871839275222246405745257275088548364400416034343698204186575808495617, address(this)
        );
    }

    // -----------------------------------------------------------------------
    // The gate
    // -----------------------------------------------------------------------

    function test_report_singleInsertGas() public {
        uint256 before = gasleft();
        tree.insert(uint256(999));
        uint256 used = before - gasleft();

        console.log("=== unbatched insertion, depth 20 ===");
        console.log("insert gas          :", used);
        console.log("+ measured verify   :", used + MEASURED_VERIFY_GAS);
        console.log("envelope            :", ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);
        console.log(
            "pct of envelope     :", (used + MEASURED_VERIFY_GAS) * 100 / ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT
        );

        assertLt(used, MAX_INSERT_SINGLE_GAS, "single insert() regressed");

        // The load-bearing claim: this path plus a verify does NOT fit, which is why the
        // sequencer must batch. If it ever starts fitting, the batching requirement needs
        // re-deriving rather than quietly becoming optional.
        //
        // Compared as a PROJECTED testnet figure, not the raw local one. Local `forge`
        // undercharges by 32-55% on every measured action, so comparing a local number
        // straight to the envelope is the exact mistake `ActionGasPolicy` warns against --
        // and it is what this assertion used to do. Raising the envelope to 2,500,000
        // made the local figure "fit" and failed this test, which is the test working:
        // the premise deserved re-checking, and on real gas it still holds.
        //
        // Projected at the LOWEST measured ratio, because this proves something does NOT
        // fit -- the conservative direction is the one that makes fitting easiest.
        uint256 projected = (used + MEASURED_VERIFY_GAS) * ActionGasPolicy.MIN_LOCAL_TO_TESTNET_PCT / 100;
        console.log("projected testnet   :", projected);

        assertGt(
            projected,
            ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT,
            "unbatched insert now fits the envelope even projected -- re-derive the batching rule"
        );
    }

    function test_report_subtreeGasPerLeaf() public {
        console.log("=== SUBTREE grafting, depth 20 (production path) ===");
        console.log("batch, total gas, per leaf");

        uint256[6] memory sizes = [uint256(1), 2, 8, 32, 64, 128];

        for (uint256 s = 0; s < sizes.length; s++) {
            uint256 n = sizes[s];

            IncrementalMerkleTree t = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
            uint256[] memory leaves = new uint256[](n);
            for (uint256 i = 0; i < n; i++) {
                leaves[i] = 5000 + i;
            }

            uint256 before = gasleft();
            t.insertSubtree(leaves);
            uint256 used = before - gasleft();

            uint256 perLeaf = used / n;
            console.log(n, used, perLeaf);
            console.log(
                "   -> per bet with verify:",
                perLeaf + MEASURED_VERIFY_GAS,
                (perLeaf + MEASURED_VERIFY_GAS) * 100 / ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT
            );

            if (n == 1) {
                assertLt(used, MAX_SUBTREE_N1_GAS, "insertSubtree at n=1 regressed");
            }
            if (n == 64) {
                assertLt(perLeaf, MAX_SUBTREE_PER_LEAF_N64, "insertSubtree per-leaf at N=64 regressed");
            }

            // Every batch size from 2 up must leave room for a verify in the envelope.
            if (n > 1) {
                assertLt(
                    perLeaf + MEASURED_VERIFY_GAS,
                    ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT,
                    "batched bet no longer fits the envelope"
                );
            }
        }
    }

    /// @notice Quantify what subtree grafting actually buys over the naive loop.
    function test_report_subtreeVsSequentialSaving() public {
        uint256 n = 64;
        uint256[] memory leaves = new uint256[](n);
        for (uint256 i = 0; i < n; i++) {
            leaves[i] = 3000 + i;
        }

        IncrementalMerkleTree a = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
        uint256 b1 = gasleft();
        a.insertSubtree(leaves);
        uint256 subtreeGas = b1 - gasleft();

        IncrementalMerkleTree b = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
        uint256 b2 = gasleft();
        b.insertBatchSequential(leaves);
        uint256 seqGas = b2 - gasleft();

        console.log("=== N=64: subtree graft vs sequential loop ===");
        console.log("subtree graft   :", subtreeGas, subtreeGas / n);
        console.log("sequential loop :", seqGas, seqGas / n);
        console.log("reduction factor:", seqGas / subtreeGas);

        assertLt(subtreeGas / n, MAX_SUBTREE_PER_LEAF_N64, "graft per-leaf at N=64 regressed");
        assertLt(
            seqGas / n,
            MAX_SEQUENTIAL_PER_LEAF_N64,
            "sequential per-leaf at N=64 regressed -- MEASUREMENTS.md cites this figure"
        );
        assertGe(seqGas / subtreeGas, MIN_GRAFT_REDUCTION_FACTOR, "grafting saving has collapsed");
    }

    /// @notice A nullifier MAPPING versus an indexed nullifier TREE.
    /// @dev Worth measuring rather than assuming. The reference recommends an indexed
    ///      nullifier tree to keep on-chain state root-only. But double-spend
    ///      prevention only needs set membership, and a mapping costs one fresh
    ///      SSTORE, whereas a tree insertion costs `depth` Poseidon hashes. At
    ///      28,980 gas per hash that difference is enormous, so the tradeoff should
    ///      be made against a real number.
    function test_report_nullifierMappingVsTree() public {
        NullifierMapping m = new NullifierMapping();

        uint256 before = gasleft();
        m.spend(bytes32(uint256(0xdeadbeef)));
        uint256 mappingGas = before - gasleft();

        IncrementalMerkleTree nullifierTree = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
        uint256 before2 = gasleft();
        nullifierTree.insert(uint256(0xdeadbeef));
        uint256 treeGas = before2 - gasleft();

        console.log("=== nullifier: mapping vs indexed tree ===");
        console.log("mapping (1 fresh SSTORE):", mappingGas);
        console.log("indexed tree insert     :", treeGas);
        console.log("saving per bet          :", treeGas - mappingGas);

        assertLt(mappingGas, MAX_NULLIFIER_MAPPING_GAS, "nullifier mapping regressed");
        assertLt(treeGas, MAX_NULLIFIER_TREE_GAS, "nullifier tree insert regressed");

        // The whole reason MEASUREMENTS.md deviates from the build plan here. If the
        // gap ever closes, the indexed tree becomes affordable and the deviation
        // should be revisited rather than inherited.
        assertGt(treeGas - mappingGas, 600_000, "mapping-vs-tree saving has shrunk -- revisit the nullifier decision");
    }

    /// @notice The gate itself: a realistic batched bet must fit the envelope.
    function test_gate_batchedBetFitsActionEnvelope() public {
        uint256 n = 64;

        IncrementalMerkleTree t = new IncrementalMerkleTree(poseidon, ZERO_VALUE, address(this));
        uint256[] memory leaves = new uint256[](n);
        for (uint256 i = 0; i < n; i++) {
            leaves[i] = 7000 + i;
        }

        uint256 before = gasleft();
        t.insertSubtree(leaves);
        uint256 perLeaf = (before - gasleft()) / n;

        NullifierMapping m = new NullifierMapping();
        uint256 before2 = gasleft();
        m.spend(bytes32(uint256(0xabcdef)));
        uint256 nullifierGas = before2 - gasleft();

        uint256 perBet = MEASURED_VERIFY_GAS + perLeaf + nullifierGas;

        console.log("=== GATE: batched bet (N=64) ===");
        console.log("verify              :", MEASURED_VERIFY_GAS);
        console.log("commitment, per leaf:", perLeaf);
        console.log("nullifier mapping   :", nullifierGas);
        console.log("total per bet       :", perBet);
        console.log("envelope            :", ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);

        assertLt(
            perBet, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "batched bet does not fit the uniform action envelope"
        );
    }
}

/// @dev Simplest double-spend guard: one storage slot per spent nullifier.
contract NullifierMapping {
    mapping(bytes32 => bool) public spent;

    error AlreadySpent();

    function spend(bytes32 nullifier) external {
        if (spent[nullifier]) revert AlreadySpent();
        spent[nullifier] = true;
    }
}
