// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";

import {Vault} from "../src/Vault.sol";
import {IERC20} from "../src/interfaces/IERC20.sol";
import {MockERC20} from "./mocks/MockERC20.sol";
import {IncrementalMerkleTree, IPoseidonT3} from "../src/IncrementalMerkleTree.sol";
import {MappingNullifierSet} from "../src/MappingNullifierSet.sol";
import {ParimutuelPool} from "../src/ParimutuelPool.sol";
import {ActionGasPolicy} from "../src/ActionGasPolicy.sol";
import {ShieldedPool, IDepositVerifier, IActionVerifier} from "../src/ShieldedPool.sol";
import {DepositVerifier} from "../src/verifiers/DepositVerifier.sol";
import {BetVerifier} from "../src/verifiers/BetVerifier.sol";
import {RedeemVerifier} from "../src/verifiers/RedeemVerifier.sol";

/// @notice PHASE 1 END TO END, with REAL proofs.
///
/// @dev The proofs replayed here are generated by
///      `circuits/scripts/gen_action_fixtures.mjs` and verified by snarkjs before they
///      are written. Nothing is mocked: the real snarkjs-generated verifiers run
///      against real Groth16 proofs, and the tree root the contract computes is
///      asserted equal to the root the JS mirror computed while building those proofs.
///
///      Mocking the verifier here would have hidden every failure that actually
///      matters -- public-signal ordering, the packing layout disagreeing between
///      circom and Solidity, and in-circuit Poseidon diverging from the etched
///      on-chain one. Each of those verifies fine in isolation and reverts on-chain.
contract ShieldedPoolTest is Test {
    using stdJson for string;

    MockERC20 usdc;
    Vault vault;
    IncrementalMerkleTree tree;
    MappingNullifierSet nullifiers;
    ParimutuelPool parimutuel;
    ShieldedPool pool;
    IPoseidonT3 poseidon;

    address sequencer = makeAddr("sequencer");
    address admin = address(this);
    address depositor = makeAddr("depositor");
    address resolver = makeAddr("resolver");

    /// Anvil account 0 -- the recipient baked into the redeem fixture's payoutData.
    address constant FIXTURE_RECIPIENT = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;

    uint32 constant MARKET_ID = 7;
    uint256 constant DENOM = 1e6;
    uint256 constant UNITS = 100;

    /// keccak256("atrum.shielded.empty") reduced into the BN254 scalar field. MUST
    /// equal ZERO_VALUE in circuits/scripts/atrum.mjs or every Merkle proof fails.
    uint256 constant ZERO_VALUE = uint256(keccak256("atrum.shielded.empty"))
        % 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    string fixtures;

    uint64 bettingClose;
    uint64 resolutionStart;

    function setUp() public {
        vm.warp(1_800_000_000);

        fixtures = vm.readFile("../circuits/build/action-fixtures.json");

        bytes memory code = vm.parseBytes(vm.trim(vm.readFile("../circuits/build/poseidon2-runtime.hex")));
        address addr = makeAddr("poseidonT3");
        vm.etch(addr, code);
        poseidon = IPoseidonT3(addr);

        usdc = new MockERC20();
        bettingClose = uint64(block.timestamp + 7 days);
        resolutionStart = bettingClose + 2 hours;

        vault = new Vault(IERC20(address(usdc)), DENOM, resolver, keccak256("spec"), bettingClose, resolutionStart);

        // Deploy the verifiers first so they do not consume nonces between the
        // prediction and the pool's own CREATE.
        DepositVerifier depositVerifier = new DepositVerifier();
        BetVerifier betVerifier = new BetVerifier();
        RedeemVerifier redeemVerifier = new RedeemVerifier();

        // The pool's address is needed by three contracts it in turn depends on, so it
        // is predicted rather than wired after the fact. Predicting keeps every one of
        // those roles immutable -- a post-hoc setter on the tree's sequencer would be a
        // standing privilege over the anonymity set.
        address predictedPool = vm.computeCreateAddress(address(this), vm.getNonce(address(this)) + 3);

        tree = new IncrementalMerkleTree(poseidon, ZERO_VALUE, predictedPool);
        parimutuel = new ParimutuelPool(predictedPool);
        nullifiers = new MappingNullifierSet();

        pool = new ShieldedPool(
            tree,
            nullifiers,
            parimutuel,
            IDepositVerifier(address(depositVerifier)),
            IActionVerifier(address(betVerifier)),
            IActionVerifier(address(redeemVerifier)),
            sequencer,
            admin
        );

        assertEq(address(pool), predictedPool, "pool address prediction failed");

        nullifiers.bindPool(address(pool));
        pool.registerMarket(MARKET_ID, vault);

        usdc.mint(depositor, 1_000_000 * DENOM);
        vm.prank(depositor);
        usdc.approve(address(pool), type(uint256).max);
    }

    // -----------------------------------------------------------------------
    // Fixture helpers
    // -----------------------------------------------------------------------

    function _u(string memory key) internal view returns (uint256) {
        return fixtures.readUint(key);
    }

    function _pA(string memory action) internal view returns (uint256[2] memory) {
        return [_u(string.concat(".", action, ".pA[0]")), _u(string.concat(".", action, ".pA[1]"))];
    }

    function _pB(string memory action) internal view returns (uint256[2][2] memory) {
        return [
            [_u(string.concat(".", action, ".pB[0][0]")), _u(string.concat(".", action, ".pB[0][1]"))],
            [_u(string.concat(".", action, ".pB[1][0]")), _u(string.concat(".", action, ".pB[1][1]"))]
        ];
    }

    function _pC(string memory action) internal view returns (uint256[2] memory) {
        return [_u(string.concat(".", action, ".pC[0]")), _u(string.concat(".", action, ".pC[1]"))];
    }

    function _batch(string memory key) internal view returns (uint256[] memory) {
        return fixtures.readUintArray(key);
    }

    // -----------------------------------------------------------------------
    // Lifecycle
    // -----------------------------------------------------------------------

    function _doDeposit() internal {
        vm.prank(depositor);
        pool.deposit(_pA("deposit"), _pB("deposit"), _pC("deposit"), _u(".deposit.commitment"), MARKET_ID, UNITS);
    }

    /// @dev Queue the fixture's filler leaves, then graft the batch.
    ///
    ///      Only the REAL commitments are submitted. The contract derives the rest of the
    ///      subtree itself, so there is nothing for the sequencer to supply and nothing it
    ///      can choose. The fixture's own filler values must equal the derived ones or the
    ///      grafted root will not match the root the proofs were built against -- asserted
    ///      in `test_derivedFillerMatchesJsMirror`.
    function _flush(string memory realKey) internal {
        uint256[] memory real = _batch(realKey);
        vm.prank(sequencer);
        pool.flushBatch(real);
    }

    function test_deposit_pullsCollateralAndQueuesCommitment() public {
        uint256 before = usdc.balanceOf(depositor);

        _doDeposit();

        assertEq(before - usdc.balanceOf(depositor), UNITS * DENOM, "collateral not pulled");
        assertEq(pool.queuedCount(), 1, "commitment not queued");
        assertEq(vault.yesBalance(address(pool)), UNITS, "pool holds no YES");
        assertEq(vault.noBalance(address(pool)), UNITS, "pool holds no NO");
    }

    /// @notice The check that makes every other test meaningful: the contract's root
    ///         must equal the root the prover built its Merkle path against.
    function test_contractRootMatchesProverRoot() public {
        _doDeposit();
        _flush(".batch1Real");

        assertEq(
            tree.root(),
            _u(".rootAfterBatch1"),
            "on-chain root disagrees with the JS mirror -- Merkle proofs cannot verify"
        );
    }

    function test_bet_spendsNoteAndMovesOdds() public {
        _doDeposit();
        _flush(".batch1Real");

        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );

        assertTrue(nullifiers.isSpent(_u(".bet.nullifierHash")), "nullifier not burned");
        assertEq(parimutuel.totalUnits(MARKET_ID), UNITS, "stake not recorded");
        assertEq(parimutuel.yesProbabilityBps(MARKET_ID), 10_000, "one-sided pool should read 100%");
        // Only REAL commitments occupy the queue now -- the deposit and the bet's
        // replacement note. Padding is derived inside `flushBatch` and never queued, so
        // the queue length is a true count of user actions rather than actions plus filler.
        assertEq(pool.queuedCount(), 2, "position commitment not queued");
        assertEq(pool.insertedCount(), 1, "only the deposit should be grafted so far");
        // Slot 1, not 64: padding no longer occupies queue slots.
        assertEq(pool.pendingCommitments(1), _u(".bet.newCommitment"), "queued commitment is not the new position");
    }

    function test_bet_rejectsReplay() public {
        _doDeposit();
        _flush(".batch1Real");

        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );

        vm.expectRevert(ShieldedPool.NullifierAlreadySpent.selector);
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );
    }

    /// @notice A structurally valid proof against a tree the contract never built.
    /// @dev This is what `isKnownRoot` is for. The proof itself verifies -- the prover
    ///      really does know a note in *some* tree. Without the root check, anyone could
    ///      invent a tree containing a note they never paid for and spend it.
    function test_bet_rejectsProofAgainstUnknownRoot() public {
        _doDeposit();
        _flush(".batch1Real");

        vm.expectRevert(ShieldedPool.UnknownRoot.selector);
        pool.bet(
            _pA("betAgainstUnknownRoot"),
            _pB("betAgainstUnknownRoot"),
            _pC("betAgainstUnknownRoot"),
            _u(".betAgainstUnknownRoot.root"),
            _u(".betAgainstUnknownRoot.nullifierHash"),
            _u(".betAgainstUnknownRoot.newCommitment"),
            _u(".betAgainstUnknownRoot.betData")
        );
    }

    function test_bet_rejectsTamperedPublicSignal() public {
        _doDeposit();
        _flush(".batch1Real");

        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment") ^ 1, // one bit
            _u(".bet.betData")
        );
    }

    function test_fullLifecycle_depositBetResolveRedeem() public {
        _doDeposit();
        _flush(".batch1Real");

        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );

        _flush(".batch2Real");
        assertEq(tree.root(), _u(".rootAfterBatch2"), "root diverged after second batch");

        vm.warp(resolutionStart + 1);
        vm.prank(resolver);
        vault.resolve(Vault.Outcome.Yes);

        uint256 before = usdc.balanceOf(FIXTURE_RECIPIENT);

        pool.redeem(
            _pA("redeem"),
            _pB("redeem"),
            _pC("redeem"),
            _u(".redeem.root"),
            _u(".redeem.nullifierHash"),
            _u(".redeem.payoutData"),
            _u(".redeem.marketMeta")
        );

        // Sole bettor on the winning side, so the payout is the whole staked pool.
        assertEq(usdc.balanceOf(FIXTURE_RECIPIENT) - before, UNITS * DENOM, "winner did not receive the pool");
        assertTrue(nullifiers.isSpent(_u(".redeem.nullifierHash")), "position not burned");
    }

    function test_redeem_revertsBeforeResolution() public {
        _doDeposit();
        _flush(".batch1Real");
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );
        _flush(".batch2Real");

        vm.expectRevert(ShieldedPool.NotResolved.selector);
        pool.redeem(
            _pA("redeem"),
            _pB("redeem"),
            _pC("redeem"),
            _u(".redeem.root"),
            _u(".redeem.nullifierHash"),
            _u(".redeem.payoutData"),
            _u(".redeem.marketMeta")
        );
    }

    function test_redeem_revertsForLosingSide() public {
        _doDeposit();
        _flush(".batch1Real");
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );
        _flush(".batch2Real");

        vm.warp(resolutionStart + 1);
        vm.prank(resolver);
        vault.resolve(Vault.Outcome.No); // fixture bet YES

        vm.expectRevert(ShieldedPool.LosingPosition.selector);
        pool.redeem(
            _pA("redeem"),
            _pB("redeem"),
            _pC("redeem"),
            _u(".redeem.root"),
            _u(".redeem.nullifierHash"),
            _u(".redeem.payoutData"),
            _u(".redeem.marketMeta")
        );
    }

    // -----------------------------------------------------------------------
    // Sequencer constraints
    // -----------------------------------------------------------------------

    function test_flushBatch_onlySequencer() public {
        _doDeposit();

        vm.expectRevert(ShieldedPool.NotSequencer.selector);
        pool.flushBatch(_batch(".batch1Real"));
    }

    /// @notice The sequencer cannot graft leaves nobody queued.
    /// @dev Without the calldata-vs-queue check, the sequencer could insert commitments
    ///      of its own and hand itself spendable notes.
    function test_flushBatch_rejectsLeavesNobodyQueued() public {
        _doDeposit();

        uint256[] memory forged = new uint256[](1);
        forged[0] = 12345;

        vm.prank(sequencer);
        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.flushBatch(forged);
    }

    /// @notice A partial batch grafts, padded by the contract. This is the liveness
    ///         property the removed `queuePadding` used to provide -- without it the last
    ///         63 users of a quiet market would wait forever for a 64th.
    function test_flushBatch_graftsPartialBatchWithDerivedPadding() public {
        _doDeposit();

        uint256[] memory short = new uint256[](1);
        short[0] = _u(".deposit.commitment");

        vm.prank(sequencer);
        pool.flushBatch(short);

        assertEq(pool.insertedCount(), 1, "only the real commitment is consumed");
        assertEq(tree.nextIndex(), 64, "a full aligned subtree must still be grafted");
    }

    /// @notice Submitting more leaves than are actually queued is rejected.
    function test_flushBatch_rejectsMoreLeavesThanQueued() public {
        _doDeposit();

        uint256[] memory tooMany = new uint256[](2);
        tooMany[0] = _u(".deposit.commitment");
        tooMany[1] = 999;

        vm.prank(sequencer);
        vm.expectRevert(ShieldedPool.NotEnoughQueued.selector);
        pool.flushBatch(tooMany);
    }

    /// @notice Nothing queued means nothing to flush.
    function test_flushBatch_rejectsEmptyQueue() public {
        uint256[] memory one = new uint256[](1);
        one[0] = 1;

        vm.prank(sequencer);
        vm.expectRevert(ShieldedPool.NotEnoughQueued.selector);
        pool.flushBatch(one);
    }

    // -----------------------------------------------------------------------
    // The gate: a real bet, measured
    // -----------------------------------------------------------------------

    function test_gate_realBetFitsActionEnvelope() public {
        _doDeposit();
        _flush(".batch1Real");

        // Hoist every fixture read OUT of the measured region. `_pA`/`_u` run
        // `vm.parseJson` cheatcodes, which cost ~1M gas of harness overhead -- inside
        // the measurement they would be reported as protocol cost and the gate would
        // fail on an artefact of the test harness.
        uint256[2] memory pA = _pA("bet");
        uint256[2][2] memory pB = _pB("bet");
        uint256[2] memory pC = _pC("bet");
        uint256 root = _u(".bet.root");
        uint256 nh = _u(".bet.nullifierHash");
        uint256 newCommitment = _u(".bet.newCommitment");
        uint256 betData = _u(".bet.betData");

        uint256 before = gasleft();
        pool.bet(pA, pB, pC, root, nh, newCommitment, betData);
        uint256 used = before - gasleft();

        console.log("=== REAL bet(), end to end ===");
        console.log("gas used   :", used);
        console.log("envelope   :", ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);
        console.log("utilisation:", used * 100 / ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);

        assertLt(used, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "a real bet does not fit the uniform action envelope");
    }

    function test_gate_realDepositAndRedeemFitEnvelope() public {
        // Same hoisting as above: cheatcode parsing must not land inside the measurement.
        uint256[2] memory dpA = _pA("deposit");
        uint256[2][2] memory dpB = _pB("deposit");
        uint256[2] memory dpC = _pC("deposit");
        uint256 dCommitment = _u(".deposit.commitment");

        vm.prank(depositor);
        uint256 before = gasleft();
        pool.deposit(dpA, dpB, dpC, dCommitment, MARKET_ID, UNITS);
        uint256 depositGas = before - gasleft();

        _flush(".batch1Real");
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );
        _flush(".batch2Real");

        vm.warp(resolutionStart + 1);
        vm.prank(resolver);
        vault.resolve(Vault.Outcome.Yes);

        uint256[2] memory rpA = _pA("redeem");
        uint256[2][2] memory rpB = _pB("redeem");
        uint256[2] memory rpC = _pC("redeem");
        uint256 rRoot = _u(".redeem.root");
        uint256 rNh = _u(".redeem.nullifierHash");
        uint256 rPayout = _u(".redeem.payoutData");
        uint256 rMeta = _u(".redeem.marketMeta");

        uint256 before2 = gasleft();
        pool.redeem(rpA, rpB, rpC, rRoot, rNh, rPayout, rMeta);
        uint256 redeemGas = before2 - gasleft();

        console.log("=== REAL deposit() / redeem() ===");
        console.log("deposit gas:", depositGas);
        console.log("redeem gas :", redeemGas);

        assertLt(depositGas, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "deposit overflows envelope");
        assertLt(redeemGas, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "redeem overflows envelope");
    }

    /// @notice The sequencer's batch is a separate transaction and only has to fit the
    ///         30,000,000 transaction limit, not the action envelope.
    function test_flushBatch_fitsTransactionLimit() public {
        _doDeposit();

        // Worst case for the contract: one real leaf, so it derives all 63 fillers.
        uint256[] memory leaves = new uint256[](1);
        leaves[0] = pool.pendingCommitments(0);

        vm.prank(sequencer);
        uint256 before = gasleft();
        pool.flushBatch(leaves);
        uint256 used = before - gasleft();

        console.log("=== sequencer flushBatch(64) ===");
        console.log("total gas:", used);
        console.log("per leaf :", used / 64);

        assertLt(used, 30_000_000, "batch exceeds the transaction gas limit");
    }
}
