// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";

import {Vault} from "../src/Vault.sol";
import {IERC20} from "../src/interfaces/IERC20.sol";
import {MockERC20} from "./mocks/MockERC20.sol";
import {IncrementalMerkleTree, IPoseidonT3} from "../src/IncrementalMerkleTree.sol";
import {MappingNullifierSet} from "../src/MappingNullifierSet.sol";
import {ParimutuelPool} from "../src/ParimutuelPool.sol";
import {ActionGasPolicy} from "../src/ActionGasPolicy.sol";
import {ShieldedPool, IDepositVerifier, IActionVerifier, IActionVerifier8} from "../src/ShieldedPool.sol";
import {ElGamalAccumulator} from "../src/ElGamalAccumulator.sol";
import {DepositVerifier} from "../src/verifiers/DepositVerifier.sol";
import {BetVerifier} from "../src/verifiers/BetVerifier.sol";
import {BetEncryptedVerifier} from "../src/verifiers/BetEncryptedVerifier.sol";

/// @notice PHASE 1 END TO END, with REAL proofs.
///
/// @dev The proofs replayed here are generated by
///      `circuits/scripts/gen_action_fixtures.mjs` and verified by snarkjs before they
///      are written. Nothing is mocked: the real snarkjs-generated verifiers run
///      against real Groth16 proofs, and the tree root the contract computes is
///      asserted equal to the root the JS mirror computed while building those proofs.
///
///      Mocking the verifier here would have hidden every failure that actually
///      matters -- public-signal ordering, the packing layout disagreeing between
///      circom and Solidity, and in-circuit Poseidon diverging from the etched
///      on-chain one. Each of those verifies fine in isolation and reverts on-chain.
/// @dev NOTE: the public `redeem()` was removed -- it published a recipient address and a
///      payout amount, which both build plans forbid. The lifecycle tests that exercised it
///      (`test_fullLifecycle_depositBetResolveRedeem`,
///      `test_gate_realDepositAndRedeemFitEnvelope`, and the two redeem revert cases) went
///      with it. The replacement path is covered end to end in `PrivateRedeem.t.sol`:
///      bet -> settle -> redeemPrivate -> withdraw, with the payout never public.
contract ShieldedPoolTest is Test {
    using stdJson for string;

    MockERC20 usdc;
    Vault vault;
    Vault encryptedVault;
    IncrementalMerkleTree tree;
    MappingNullifierSet nullifiers;
    ParimutuelPool parimutuel;
    ElGamalAccumulator accumulator;
    ShieldedPool pool;
    IPoseidonT3 poseidon;

    address sequencer = makeAddr("sequencer");
    address admin = address(this);
    address depositor = makeAddr("depositor");
    address resolver = makeAddr("resolver");

    /// Anvil account 0 -- the recipient baked into the redeem fixture's payoutData.
    address constant FIXTURE_RECIPIENT = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;

    uint32 constant MARKET_ID = 7;

    /// @dev Phase 2 market. Separate from MARKET_ID because a market's pool total lives
    ///      either in `parimutuel` or in `accumulator`, never both.
    uint32 constant ENCRYPTED_MARKET_ID = 8;

    uint256 constant DENOM = 1e6;
    uint256 constant UNITS = 100;

    /// keccak256("atrum.shielded.empty") reduced into the BN254 scalar field. MUST
    /// equal ZERO_VALUE in circuits/scripts/atrum.mjs or every Merkle proof fails.
    uint256 constant ZERO_VALUE = uint256(keccak256("atrum.shielded.empty"))
        % 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    string fixtures;

    uint64 bettingClose;
    uint64 resolutionStart;

    function setUp() public {
        vm.warp(1_800_000_000);

        fixtures = vm.readFile("../circuits/build/action-fixtures.json");

        bytes memory code = vm.parseBytes(vm.trim(vm.readFile("../circuits/build/poseidon2-runtime.hex")));
        address addr = makeAddr("poseidonT3");
        vm.etch(addr, code);
        poseidon = IPoseidonT3(addr);

        usdc = new MockERC20();
        bettingClose = uint64(block.timestamp + 7 days);
        resolutionStart = bettingClose + 2 hours;

        vault = new Vault(IERC20(address(usdc)), DENOM, resolver, keccak256("spec"), bettingClose, resolutionStart);
        encryptedVault =
            new Vault(IERC20(address(usdc)), DENOM, resolver, keccak256("spec-enc"), bettingClose, resolutionStart);

        // Deploy the verifiers first so they do not consume nonces between the
        // prediction and the pool's own CREATE.
        DepositVerifier depositVerifier = new DepositVerifier();
        BetVerifier betVerifier = new BetVerifier();
        BetEncryptedVerifier betEncryptedVerifier = new BetEncryptedVerifier();

        // The pool's address is needed by three contracts it in turn depends on, so it
        // is predicted rather than wired after the fact. Predicting keeps every one of
        // those roles immutable -- a post-hoc setter on the tree's sequencer would be a
        // standing privilege over the anonymity set.
        address predictedPool = vm.computeCreateAddress(address(this), vm.getNonce(address(this)) + 4);

        tree = new IncrementalMerkleTree(poseidon, ZERO_VALUE, predictedPool);
        parimutuel = new ParimutuelPool(predictedPool);
        nullifiers = new MappingNullifierSet();
        accumulator = new ElGamalAccumulator(predictedPool);

        pool = new ShieldedPool(
            tree,
            nullifiers,
            parimutuel,
            accumulator,
            IDepositVerifier(address(depositVerifier)),
            IActionVerifier(address(betVerifier)),
            IActionVerifier8(address(betEncryptedVerifier)),
            sequencer,
            admin
        );

        assertEq(address(pool), predictedPool, "pool address prediction failed");

        nullifiers.bindPool(address(pool));
        pool.registerMarket(MARKET_ID, vault);
        pool.registerEncryptedMarket(ENCRYPTED_MARKET_ID, encryptedVault);

        usdc.mint(depositor, 1_000_000 * DENOM);
        vm.prank(depositor);
        usdc.approve(address(pool), type(uint256).max);
    }

    // -----------------------------------------------------------------------
    // Fixture helpers
    // -----------------------------------------------------------------------

    function _u(string memory key) internal view returns (uint256) {
        return fixtures.readUint(key);
    }

    function _pA(string memory action) internal view returns (uint256[2] memory) {
        return [_u(string.concat(".", action, ".pA[0]")), _u(string.concat(".", action, ".pA[1]"))];
    }

    function _pB(string memory action) internal view returns (uint256[2][2] memory) {
        return [
            [_u(string.concat(".", action, ".pB[0][0]")), _u(string.concat(".", action, ".pB[0][1]"))],
            [_u(string.concat(".", action, ".pB[1][0]")), _u(string.concat(".", action, ".pB[1][1]"))]
        ];
    }

    function _pC(string memory action) internal view returns (uint256[2] memory) {
        return [_u(string.concat(".", action, ".pC[0]")), _u(string.concat(".", action, ".pC[1]"))];
    }

    function _batch(string memory key) internal view returns (uint256[] memory) {
        return fixtures.readUintArray(key);
    }

    // -----------------------------------------------------------------------
    // Lifecycle
    // -----------------------------------------------------------------------

    function _doDeposit() internal {
        vm.prank(depositor);
        pool.deposit(_pA("deposit"), _pB("deposit"), _pC("deposit"), _u(".deposit.commitment"), MARKET_ID, UNITS);
    }

    /// @dev Queue the fixture's filler leaves, then graft the batch.
    ///
    ///      Only the REAL commitments are submitted. The contract derives the rest of the
    ///      subtree itself, so there is nothing for the sequencer to supply and nothing it
    ///      can choose. The fixture's own filler values must equal the derived ones or the
    ///      grafted root will not match the root the proofs were built against -- asserted
    ///      in `test_derivedFillerMatchesJsMirror`.
    function _flush(string memory realKey) internal {
        uint256[] memory real = _batch(realKey);
        vm.prank(sequencer);
        pool.flushBatch(real);
    }

    function test_deposit_pullsCollateralAndQueuesCommitment() public {
        uint256 before = usdc.balanceOf(depositor);

        _doDeposit();

        assertEq(before - usdc.balanceOf(depositor), UNITS * DENOM, "collateral not pulled");
        assertEq(pool.queuedCount(), 1, "commitment not queued");
        assertEq(vault.yesBalance(address(pool)), UNITS, "pool holds no YES");
        assertEq(vault.noBalance(address(pool)), UNITS, "pool holds no NO");
    }

    /// @notice The check that makes every other test meaningful: the contract's root
    ///         must equal the root the prover built its Merkle path against.
    function test_contractRootMatchesProverRoot() public {
        _doDeposit();
        _flush(".batch1Real");

        assertEq(
            tree.root(),
            _u(".rootAfterBatch1"),
            "on-chain root disagrees with the JS mirror -- Merkle proofs cannot verify"
        );
    }

    function test_bet_spendsNoteAndMovesOdds() public {
        _doDeposit();
        _flush(".batch1Real");

        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );

        assertTrue(nullifiers.isSpent(_u(".bet.nullifierHash")), "nullifier not burned");
        assertEq(parimutuel.totalUnits(MARKET_ID), UNITS, "stake not recorded");
        assertEq(parimutuel.yesProbabilityBps(MARKET_ID), 10_000, "one-sided pool should read 100%");
        // Only REAL commitments occupy the queue now -- the deposit and the bet's
        // replacement note. Padding is derived inside `flushBatch` and never queued, so
        // the queue length is a true count of user actions rather than actions plus filler.
        assertEq(pool.queuedCount(), 2, "position commitment not queued");
        assertEq(pool.insertedCount(), 1, "only the deposit should be grafted so far");
        // Slot 1, not 64: padding no longer occupies queue slots.
        assertEq(pool.pendingCommitments(1), _u(".bet.newCommitment"), "queued commitment is not the new position");
    }

    function test_bet_rejectsReplay() public {
        _doDeposit();
        _flush(".batch1Real");

        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );

        vm.expectRevert(ShieldedPool.NullifierAlreadySpent.selector);
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );
    }

    /// @notice A structurally valid proof against a tree the contract never built.
    /// @dev This is what `isKnownRoot` is for. The proof itself verifies -- the prover
    ///      really does know a note in *some* tree. Without the root check, anyone could
    ///      invent a tree containing a note they never paid for and spend it.
    function test_bet_rejectsProofAgainstUnknownRoot() public {
        _doDeposit();
        _flush(".batch1Real");

        vm.expectRevert(ShieldedPool.UnknownRoot.selector);
        pool.bet(
            _pA("betAgainstUnknownRoot"),
            _pB("betAgainstUnknownRoot"),
            _pC("betAgainstUnknownRoot"),
            _u(".betAgainstUnknownRoot.root"),
            _u(".betAgainstUnknownRoot.nullifierHash"),
            _u(".betAgainstUnknownRoot.newCommitment"),
            _u(".betAgainstUnknownRoot.betData")
        );
    }

    function test_bet_rejectsTamperedPublicSignal() public {
        _doDeposit();
        _flush(".batch1Real");

        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment") ^ 1, // one bit
            _u(".bet.betData")
        );
    }

    // -----------------------------------------------------------------------
    // Sequencer constraints
    // -----------------------------------------------------------------------

    function test_flushBatch_onlySequencer() public {
        _doDeposit();

        vm.expectRevert(ShieldedPool.NotSequencer.selector);
        pool.flushBatch(_batch(".batch1Real"));
    }

    /// @notice The sequencer cannot graft leaves nobody queued.
    /// @dev Without the calldata-vs-queue check, the sequencer could insert commitments
    ///      of its own and hand itself spendable notes.
    function test_flushBatch_rejectsLeavesNobodyQueued() public {
        _doDeposit();

        uint256[] memory forged = new uint256[](1);
        forged[0] = 12345;

        vm.prank(sequencer);
        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.flushBatch(forged);
    }

    /// @notice A partial batch grafts, padded by the contract. This is the liveness
    ///         property the removed `queuePadding` used to provide -- without it the last
    ///         63 users of a quiet market would wait forever for a 64th.
    function test_flushBatch_graftsPartialBatchWithDerivedPadding() public {
        _doDeposit();

        uint256[] memory short = new uint256[](1);
        short[0] = _u(".deposit.commitment");

        vm.prank(sequencer);
        pool.flushBatch(short);

        assertEq(pool.insertedCount(), 1, "only the real commitment is consumed");
        assertEq(tree.nextIndex(), 64, "a full aligned subtree must still be grafted");
    }

    /// @notice Submitting more leaves than are actually queued is rejected.
    function test_flushBatch_rejectsMoreLeavesThanQueued() public {
        _doDeposit();

        uint256[] memory tooMany = new uint256[](2);
        tooMany[0] = _u(".deposit.commitment");
        tooMany[1] = 999;

        vm.prank(sequencer);
        vm.expectRevert(ShieldedPool.NotEnoughQueued.selector);
        pool.flushBatch(tooMany);
    }

    /// @notice Nothing queued means nothing to flush.
    function test_flushBatch_rejectsEmptyQueue() public {
        uint256[] memory one = new uint256[](1);
        one[0] = 1;

        vm.prank(sequencer);
        vm.expectRevert(ShieldedPool.NotEnoughQueued.selector);
        pool.flushBatch(one);
    }

    // -----------------------------------------------------------------------
    // The gate: a real bet, measured
    // -----------------------------------------------------------------------

    /// @notice A real `deposit` fits the uniform action envelope.
    ///
    /// @dev Restored after being lost. The original gate measured deposit and the public
    ///      `redeem` together; when `redeem` was removed the whole test went with it, silently
    ///      taking deposit's only envelope gate along. Deposit is still a live action, so it
    ///      still needs one.
    ///
    ///      Every cheatcode read is hoisted above `gasleft()`. `vm.parseJson` costs on the
    ///      order of 450,000 gas and has landed inside a measurement bracket three separate
    ///      times in this repo, each time inflating a reported number by more than the action
    ///      itself costs.
    function test_gate_realDepositFitsActionEnvelope() public {
        uint256[2] memory dpA = _pA("deposit");
        uint256[2][2] memory dpB = _pB("deposit");
        uint256[2] memory dpC = _pC("deposit");
        uint256 dCommitment = _u(".deposit.commitment");

        vm.prank(depositor);
        uint256 before = gasleft();
        pool.deposit(dpA, dpB, dpC, dCommitment, MARKET_ID, UNITS);
        uint256 used = before - gasleft();

        console.log("=== REAL deposit() ===");
        console.log("gas        :", used);
        console.log("envelope   :", ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);
        console.log("utilisation:", used * 100 / ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);

        assertLt(used, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "a real deposit does not fit the uniform envelope");
    }

    function test_gate_realBetFitsActionEnvelope() public {
        _doDeposit();
        _flush(".batch1Real");

        // Hoist every fixture read OUT of the measured region. `_pA`/`_u` run
        // `vm.parseJson` cheatcodes, which cost ~1M gas of harness overhead -- inside
        // the measurement they would be reported as protocol cost and the gate would
        // fail on an artefact of the test harness.
        uint256[2] memory pA = _pA("bet");
        uint256[2][2] memory pB = _pB("bet");
        uint256[2] memory pC = _pC("bet");
        uint256 root = _u(".bet.root");
        uint256 nh = _u(".bet.nullifierHash");
        uint256 newCommitment = _u(".bet.newCommitment");
        uint256 betData = _u(".bet.betData");

        uint256 before = gasleft();
        pool.bet(pA, pB, pC, root, nh, newCommitment, betData);
        uint256 used = before - gasleft();

        console.log("=== REAL bet(), end to end ===");
        console.log("gas used   :", used);
        console.log("envelope   :", ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);
        console.log("utilisation:", used * 100 / ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);

        assertLt(used, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "a real bet does not fit the uniform action envelope");
    }

    /// @notice The sequencer's batch is a separate transaction and only has to fit the
    ///         30,000,000 transaction limit, not the action envelope.
    function test_flushBatch_fitsTransactionLimit() public {
        _doDeposit();

        // Worst case for the contract: one real leaf, so it derives all 63 fillers.
        uint256[] memory leaves = new uint256[](1);
        leaves[0] = pool.pendingCommitments(0);

        vm.prank(sequencer);
        uint256 before = gasleft();
        pool.flushBatch(leaves);
        uint256 used = before - gasleft();

        console.log("=== sequencer flushBatch(64) ===");
        console.log("total gas:", used);
        console.log("per leaf :", used / 64);

        assertLt(used, 30_000_000, "batch exceeds the transaction gas limit");
    }

    // -----------------------------------------------------------------------
    // PHASE 2 -- encrypted pool total
    // -----------------------------------------------------------------------

    /// @dev Walk the tree forward to where the encrypted deposit's Merkle path was built.
    ///      Batches graft sequentially, so batch 3 cannot be reached without 1 and 2.
    function _reachEncryptedDeposit() internal {
        _doDeposit();
        _flush(".batch1Real");

        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            _u(".bet.betData")
        );
        _flush(".batch2Real");

        vm.prank(depositor);
        pool.deposit(
            _pA("depositEncrypted"),
            _pB("depositEncrypted"),
            _pC("depositEncrypted"),
            _u(".depositEncrypted.commitment"),
            ENCRYPTED_MARKET_ID,
            UNITS
        );
        _flush(".batch3Real");

        assertEq(tree.root(), _u(".rootAfterBatch3"), "root disagrees with the JS mirror at batch 3");
    }

    function _ciphertext() internal view returns (uint256[4] memory) {
        return [
            _u(".betEncrypted.ciphertext[0]"),
            _u(".betEncrypted.ciphertext[1]"),
            _u(".betEncrypted.ciphertext[2]"),
            _u(".betEncrypted.ciphertext[3]")
        ];
    }

    function _doBetEncrypted() internal {
        pool.betEncrypted(
            _pA("betEncrypted"),
            _pB("betEncrypted"),
            _pC("betEncrypted"),
            _u(".betEncrypted.root"),
            _u(".betEncrypted.nullifierHash"),
            _u(".betEncrypted.newCommitment"),
            _u(".betEncrypted.betMeta"),
            _ciphertext()
        );
    }

    /// @notice The Phase 2 milestone, with a real proof: a stake enters the pool without
    ///         the contract ever seeing its value.
    function test_betEncrypted_accumulatesWithoutRevealingStake() public {
        _reachEncryptedDeposit();

        (uint256 c1xBefore, uint256 c1yBefore,,) = accumulator.totalAffine(ENCRYPTED_MARKET_ID, 1);
        assertEq(c1xBefore, 0, "accumulator should start at the identity");
        assertEq(c1yBefore, 1, "identity is (0,1), not all-zeros");

        _doBetEncrypted();

        assertTrue(nullifiers.isSpent(_u(".betEncrypted.nullifierHash")), "nullifier not burned");

        (uint256 c1x, uint256 c1y, uint256 c2x, uint256 c2y) = accumulator.totalAffine(ENCRYPTED_MARKET_ID, 1);
        assertEq(c1x, _u(".betEncrypted.ciphertext[0]"), "accumulated C1.x is not the published ciphertext");
        assertEq(c1y, _u(".betEncrypted.ciphertext[1]"), "accumulated C1.y is not the published ciphertext");
        assertEq(c2x, _u(".betEncrypted.ciphertext[2]"), "accumulated C2.x is not the published ciphertext");
        assertEq(c2y, _u(".betEncrypted.ciphertext[3]"), "accumulated C2.y is not the published ciphertext");

        // The point of the whole phase: the plaintext pool total never moved, because
        // the contract was never told one.
        assertEq(parimutuel.totalUnits(ENCRYPTED_MARKET_ID), 0, "an encrypted bet must not touch the public pool");

        assertEq(pool.queuedCount(), 4, "position commitment not queued");
    }

    function test_betEncrypted_rejectsReplay() public {
        _reachEncryptedDeposit();
        _doBetEncrypted();

        vm.expectRevert(ShieldedPool.NullifierAlreadySpent.selector);
        _doBetEncrypted();
    }

    /// @notice The guard that stops a market having two disagreeing pool totals.
    function test_betEncrypted_refusesPlaintextMarket() public {
        _reachEncryptedDeposit();

        // betMeta for market 7, which is registered on the Phase 1 path.
        uint256 plaintextMeta = uint256(MARKET_ID) * 4 + 1;

        vm.expectRevert(ShieldedPool.WrongActionForMarket.selector);
        pool.betEncrypted(
            _pA("betEncrypted"),
            _pB("betEncrypted"),
            _pC("betEncrypted"),
            _u(".betEncrypted.root"),
            _u(".betEncrypted.nullifierHash"),
            _u(".betEncrypted.newCommitment"),
            plaintextMeta,
            _ciphertext()
        );
    }

    /// @notice The mirror guard: a plaintext bet must not stake into an encrypted market,
    ///         which would build a public total the real odds do not derive from.
    function test_bet_refusesEncryptedMarket() public {
        _doDeposit();
        _flush(".batch1Real");

        // betData packing: marketId * 2^66 + outcome * 2^64 + units.
        uint256 encMarketBetData = (uint256(ENCRYPTED_MARKET_ID) << 66) | (uint256(1) << 64) | UNITS;

        vm.expectRevert(ShieldedPool.WrongActionForMarket.selector);
        pool.bet(
            _pA("bet"),
            _pB("bet"),
            _pC("bet"),
            _u(".bet.root"),
            _u(".bet.nullifierHash"),
            _u(".bet.newCommitment"),
            encMarketBetData
        );
    }

    /// @notice A tampered ciphertext must not verify. The consistency constraint binds
    ///         Enc(units) to the stake inside the spent note, so altering one field
    ///         element breaks the proof rather than quietly accumulating a different
    ///         amount -- which is the attack that would otherwise inflate a position.
    function test_betEncrypted_rejectsTamperedCiphertext() public {
        _reachEncryptedDeposit();

        uint256[4] memory tampered = _ciphertext();
        tampered[2] = tampered[2] + 1;

        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.betEncrypted(
            _pA("betEncrypted"),
            _pB("betEncrypted"),
            _pC("betEncrypted"),
            _u(".betEncrypted.root"),
            _u(".betEncrypted.nullifierHash"),
            _u(".betEncrypted.newCommitment"),
            _u(".betEncrypted.betMeta"),
            tampered
        );
    }

    /// @notice Registering an encrypted market must initialise the accumulator in the
    ///         same transaction. An uninitialised slot reads (0,0,0,0), which is not a
    ///         curve point, so the first bet would revert -- a state worth making
    ///         unreachable rather than merely guarded.
    function test_registerEncryptedMarket_initialisesAccumulator() public {
        assertTrue(accumulator.initialised(ENCRYPTED_MARKET_ID, 1), "YES side not initialised");
        assertTrue(accumulator.initialised(ENCRYPTED_MARKET_ID, 2), "NO side not initialised");
        assertTrue(pool.encryptedMarket(ENCRYPTED_MARKET_ID), "market not flagged encrypted");
        assertFalse(pool.encryptedMarket(MARKET_ID), "plaintext market wrongly flagged");
    }

    /// @notice Phase 2 retires the plaintext path for NEW markets, without disturbing
    ///         markets already registered.
    function test_freezeLegacyMarkets_blocksNewPlaintextMarketsOnly() public {
        pool.freezeLegacyMarkets();
        assertTrue(pool.legacyMarketsFrozen(), "freeze flag not set");

        vm.expectRevert(ShieldedPool.LegacyMarketsAreFrozen.selector);
        pool.registerMarket(99, vault);

        // Encrypted registration still works, and the existing plaintext market is
        // untouched -- freezing retires the path for new markets, it does not break
        // markets that are already live.
        pool.registerEncryptedMarket(100, encryptedVault);
        assertEq(address(pool.marketVault(MARKET_ID)), address(vault), "existing market disturbed");
    }

    /// @notice Real measured cost of the wired encrypted bet, against the uniform
    ///         envelope every shielded action is declared with.
    ///
    /// @dev Local `forge` UNDERSTATES this. It charges neither calldata nor the intrinsic
    ///      cost nor true cross-contract cold access, and measured Phase 1 actions came in
    ///      30-40% higher on a real testnet transaction than they do here (MEASUREMENTS.md
    ///      §1c). This asserts the local figure only; the envelope question is not closed
    ///      until this action is broadcast for real.
    function test_report_betEncryptedGas() public {
        _reachEncryptedDeposit();

        // Hoist every fixture read OUT of the measured region, exactly as the Phase 1
        // gate tests do. `_pA`/`_u` run `vm.parseJson` cheatcodes costing ~1M gas of
        // harness overhead; measured inline they are reported as protocol cost and the
        // gate fails on an artefact of the test harness rather than on the contract.
        uint256[2] memory pA = _pA("betEncrypted");
        uint256[2][2] memory pB = _pB("betEncrypted");
        uint256[2] memory pC = _pC("betEncrypted");
        uint256 root = _u(".betEncrypted.root");
        uint256 nh = _u(".betEncrypted.nullifierHash");
        uint256 newCommitment = _u(".betEncrypted.newCommitment");
        uint256 betMeta = _u(".betEncrypted.betMeta");
        uint256[4] memory ciphertext = _ciphertext();

        uint256 before = gasleft();
        pool.betEncrypted(pA, pB, pC, root, nh, newCommitment, betMeta, ciphertext);
        uint256 used = before - gasleft();

        console.log("=== REAL betEncrypted(), end to end ===");
        console.log("gas used   :", used);
        console.log("envelope   :", ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);
        console.log("utilisation:", used * 100 / ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT);

        assertLt(used, ActionGasPolicy.UNIFORM_ACTION_GAS_LIMIT, "encrypted bet exceeds the uniform envelope locally");
    }
}
