/**
 * Emit `src/committee_key.circom` from `build/committee-key.json`.
 *
 * Why this exists: `probe_fixed_key.circom` bakes the committee public key in at
 * compile time, but `committee-key.json` is gitignored because it holds the matching
 * SECRET. Before this script the two were kept in sync by hand, so a clean clone ran
 * `keygen` -> got a fresh key -> compiled a circuit still pinned to the previous
 * key, and every ciphertext check failed for a reason that looked like a circuit bug.
 *
 * Generating the constants instead makes that failure impossible: the compiled
 * circuit is derived from the key file rather than merely agreeing with it.
 *
 * The output is gitignored. It contains only the PUBLIC key, but it is a build
 * artefact of a gitignored input, so committing it would reintroduce the same drift.
 */
import { readFileSync, writeFileSync } from "node:fs";

const KEY = new URL("../build/committee-key.json", import.meta.url);
const OUT = new URL("../src/committee_key.circom", import.meta.url);

const { pubKey } = JSON.parse(readFileSync(KEY, "utf8"));

if (!Array.isArray(pubKey) || pubKey.length !== 2) {
  throw new Error("committee-key.json: expected pubKey to be [x, y]");
}

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen_committee_key_circom.mjs -- do not edit, do not commit.
// Derived from build/committee-key.json. Re-run \`node scripts/keygen.mjs\` to rotate.
//
// TEST KEY. Generated for gas measurement. Never use this for anything of value.
pragma circom 2.1.9;

function committeeKeyX() { return ${pubKey[0]}; }
function committeeKeyY() { return ${pubKey[1]}; }
`,
);

console.log(`wrote ${OUT.pathname}`);
console.log(`  x = ${pubKey[0]}`);
console.log(`  y = ${pubKey[1]}`);
