#!/usr/bin/env python3
"""
PHASE 0 GATE: measure real on-chain gas for a generated Groth16 verifier on Monad.

The build plan's stop-line: if a production-shaped BabyJubJub-ElGamal circuit
verifies for more than ~1.5M gas, stop and reassess the architecture.

Method: take the compiled verifier's *deployed* bytecode, inject it at a throwaway
address via an `eth_call` state override, and call `verifyProof` with a real proof
generated by `circuits/scripts/prove.mjs`. Gas is measured by the live node, using
the marginal method so the cold-account charge and probe overhead cancel exactly.

No key, no deploy, no spend -- and the number comes from Monad's real gas schedule
rather than a local EVM that does not implement its repricing.

Usage:
    python3 tools/measure_verifier.py [--network testnet|mainnet]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from monad_gas import TARGET_ADDR, measure_marginal, rpc  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
BUILD = ROOT / "circuits" / "build"

GATE_GAS = 1_500_000

# Reference figures from nisi-master-reference.md 1.3, for the verifier *core*
# (l scalar mults + adds to build vk_x, then the 4-pair check). A real generated
# verifier adds calldata handling and field-range validation on top.
REFERENCE_CORE = {4: 1_031_828, 6: None, 8: 1_157_678}

VARIANTS = [
    # (contract name, circuit name, public signal count)
    #
    # The two Phase 0 probes measure the ElGamal gate. The three Phase 1 actions are
    # here because the anti-fingerprinting rule is about ACTIONS: every shielded action
    # must fit one uniform declared gas limit, so a new action that does not fit has to
    # fail the guard rather than quietly ship with a snug limit that identifies it.
    ("FixedKeyVerifier", "probe_fixed_key", 4),
    ("PubKeyInputVerifier", "probe_pubkey_input", 6),
    ("DepositVerifier", "deposit", 3),
    ("BetVerifier", "bet", 4),
    ("RedeemVerifier", "redeem", 4),
    # Phase 2. The ciphertext is four field elements the contract has to ADD to the
    # accumulator, so unlike every other action's payload it cannot be packed or hashed
    # away -- 8 public signals is the real floor, not a design slip. Until this line
    # existed the 8-signal cost was an extrapolation from REFERENCE_CORE, never measured.
    ("BetEncryptedVerifier", "bet_encrypted", 8),
]


def forge(*args: str) -> str:
    """Run the Monad build of forge."""
    forge_bin = Path.home() / ".foundry-monad" / "bin" / "forge"
    result = subprocess.run(
        [str(forge_bin), *args],
        cwd=CONTRACTS,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def deployed_bytecode(contract: str) -> str:
    """Runtime bytecode -- what actually lives at the address, not the initcode."""
    raw = forge("inspect", contract, "deployedBytecode")
    code = json.loads(raw) if raw.startswith('"') else raw
    return code if code.startswith("0x") else "0x" + code


def selector(signature: str) -> str:
    """keccak256(signature)[:4], via cast (no keccak in the stdlib)."""
    cast_bin = Path.home() / ".foundry-monad" / "bin" / "cast"
    out = subprocess.run(
        [str(cast_bin), "sig", signature], capture_output=True, text=True, check=True
    )
    return out.stdout.strip()


def build_calldata(circuit: str, n_public: int) -> str:
    """
    ABI-encode verifyProof(uint[2],uint[2][2],uint[2],uint[N]).

    Every parameter is a fixed-size array of uint256, so the encoding is just the
    selector followed by the words in order -- no offsets, no dynamic tails.
    """
    # Read snarkjs's own `exportSolidityCallData` output rather than re-deriving
    # the encoding from proof.json.
    #
    # This matters: snarkjs SWAPS each G2 coordinate pair when it emits calldata
    # (pB[0] = [pi_b[0][1], pi_b[0][0]]), because the generated verifier expects
    # the opposite Fp2 limb order from the one the proof file stores. Re-encoding
    # from proof.json in the naive order produces a well-formed but invalid proof,
    # which reverts -- and would have been easy to misread as a gas failure.
    raw = (BUILD / f"{circuit}_calldata.json").read_text().strip()
    pa, pb, pc, public_signals = json.loads(f"[{raw}]")

    if len(public_signals) != n_public:
        raise SystemExit(
            f"{circuit}: expected {n_public} public signals, got {len(public_signals)}"
        )

    sig = f"verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[{n_public}])"

    words = [
        int(pa[0], 16), int(pa[1], 16),
        int(pb[0][0], 16), int(pb[0][1], 16),
        int(pb[1][0], 16), int(pb[1][1], 16),
        int(pc[0], 16), int(pc[1], 16),
        *(int(s, 16) for s in public_signals),
    ]

    return selector(sig) + "".join(f"{w:064x}" for w in words)


def returns_true(network: str, code: str, calldata: str) -> bool:
    """
    Confirm the verifier actually ACCEPTS the proof.

    Necessary, not paranoid: a Groth16 verifier returns `false` for an invalid
    proof without reverting. Measuring gas on a rejected proof would silently
    report the cost of the rejection path -- a number that looks plausible and
    means nothing.
    """
    result = rpc(network, "eth_call", [
        {"to": TARGET_ADDR, "data": calldata, "gas": hex(0x2000000)},
        "latest",
        {TARGET_ADDR: {"code": code}},
    ])
    return int(result, 16) == 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--network", choices=["testnet", "mainnet"], default="testnet")
    ap.add_argument("--json", metavar="PATH")
    args = ap.parse_args()

    print(f"PHASE 0 GATE -- Groth16 verify gas on Monad {args.network}")
    print(f"stop-line: {GATE_GAS:,} gas\n")

    results = {}
    gate_failed = False

    for contract, circuit, n_public in VARIANTS:
        code = deployed_bytecode(contract)
        calldata = build_calldata(circuit, n_public)

        overrides = {TARGET_ADDR: {"code": code}}

        accepted = returns_true(args.network, code, calldata)
        if not accepted:
            print(f"--- {contract} ---")
            print("  verifier REJECTED the proof -- gas figure would be meaningless")
            print("  check the G2 limb ordering in the calldata encoding\n")
            results[contract] = {"error": "proof rejected by verifier"}
            gate_failed = True
            continue

        m = measure_marginal(args.network, TARGET_ADDR, calldata, overrides)

        cost = m["cost"]
        ref = REFERENCE_CORE.get(n_public)
        verdict = "PASS" if cost <= GATE_GAS else "FAIL"
        if cost > GATE_GAS:
            gate_failed = True

        print(f"--- {contract} ({n_public} public signals) ---")
        print(f"  proof accepted        yes (returns true)")
        print(f"  runtime bytecode      {len(code) // 2 - 1:,} bytes")
        print(f"  verify gas (warm)     {cost:,}")
        print(f"  first call, cold      {m['first_call_total'] - 119:,}"
              f"   (+{m['cold_premium']:,} cold-access premium)")
        print(f"  linear across repeats {m['linear']}")
        if ref:
            delta = cost - ref
            print(f"  reference core        {ref:,}   ({delta:+,}, "
                  f"{100 * delta / ref:+.1f}% for the real verifier)")
        print(f"  vs {GATE_GAS:,} gate     {verdict}  "
              f"({100 * cost / GATE_GAS:.1f}% of budget)\n")

        results[contract] = {
            "public_signals": n_public,
            "verify_gas_warm": cost,
            "verify_gas_cold_first_call": m["first_call_total"] - 119,
            "cold_premium": m["cold_premium"],
            "linear": m["linear"],
            "bytecode_bytes": len(code) // 2 - 1,
            "reference_core": ref,
            "gate_pass": cost <= GATE_GAS,
        }

    # Cost of the two extra public inputs, measured rather than assumed.
    if len(results) == 2:
        a = results["FixedKeyVerifier"]["verify_gas_warm"]
        b = results["PubKeyInputVerifier"]["verify_gas_warm"]
        print(f"cost of 2 extra public inputs: {b - a:,} gas "
              f"({(b - a) / 2:,.0f} per input)")
        print("  -- each public input needs one ecMul (30,000 on Monad, 5x Ethereum)")
        print("     plus one ecAdd (300) to fold into vk_x.\n")

    print("GATE:", "FAILED -- stop and reassess" if gate_failed else "PASSED")

    if args.json:
        Path(args.json).write_text(json.dumps(
            {"network": args.network, "gate_gas": GATE_GAS, "results": results},
            indent=2))
        print(f"wrote {args.json}")

    return 1 if gate_failed else 0


if __name__ == "__main__":
    sys.exit(main())
