pragma circom 2.1.9;

include "elgamal.circom";

/// Phase 0 gas probe -- variant B: committee key BAKED IN at compile time.
///
/// Public signals: c1[2] + c2[2] = 4, which is the reference's stated ceiling
/// ("keep public inputs to 4 or fewer").
///
/// The trade: rotating the decryption key now means recompiling the circuit and
/// running a fresh Groth16 trusted setup. That is acceptable only because the key
/// belongs to the protocol deployment rather than to an individual market -- one
/// ceremony covers every market. It becomes a real liability at Phase 3, when the
/// single key is replaced by a 3-of-5 committee whose membership may change.
///
/// TEST KEY ONLY -- generated by `scripts/keygen.mjs` for measurement. A real
/// deployment bakes in a key produced by an actual setup ceremony.
template ElGamalFixedKey(AMOUNT_BITS) {
    signal input amount;
    signal input randomness;

    signal output c1[2];
    signal output c2[2];

    var HX = 12655537635611010226664245908130306495897187944548266400849103501241618924694;
    var HY = 16245990228332108457883877877689040044492849160046067425265081936854048772021;

    component enc = ElGamalEncrypt(AMOUNT_BITS);
    enc.amount <== amount;
    enc.randomness <== randomness;
    enc.pubKey[0] <== HX;
    enc.pubKey[1] <== HY;

    c1[0] <== enc.c1[0];
    c1[1] <== enc.c1[1];
    c2[0] <== enc.c2[0];
    c2[1] <== enc.c2[1];
}

component main = ElGamalFixedKey(40);
