pragma circom 2.1.9;

include "elgamal.circom";
include "committee_key.circom";

/// Phase 0 gas probe -- variant B: committee key BAKED IN at compile time.
///
/// Public signals: c1[2] + c2[2] = 4, which is the reference's stated ceiling
/// ("keep public inputs to 4 or fewer").
///
/// The trade: rotating the decryption key now means recompiling the circuit and
/// running a fresh Groth16 trusted setup. That is acceptable only because the key
/// belongs to the protocol deployment rather than to an individual market -- one
/// ceremony covers every market. It becomes a real liability at Phase 3, when the
/// single key is replaced by a 3-of-5 committee whose membership may change.
///
/// TEST KEY ONLY -- generated by `scripts/keygen.mjs` for measurement. A real
/// deployment bakes in a key produced by an actual setup ceremony.
///
/// The constants come from the GENERATED `committee_key.circom`, derived from
/// `build/committee-key.json` by `scripts/gen_committee_key_circom.mjs`. They used to
/// be literals here, which meant a clean clone regenerated a fresh key and then
/// compiled a circuit still pinned to the old one -- every ciphertext check failed
/// looking like a circuit bug. Deriving them removes that failure mode entirely.
template ElGamalFixedKey(AMOUNT_BITS) {
    signal input amount;
    signal input randomness;

    signal output c1[2];
    signal output c2[2];

    var HX = committeeKeyX();
    var HY = committeeKeyY();

    component enc = ElGamalEncrypt(AMOUNT_BITS);
    enc.amount <== amount;
    enc.randomness <== randomness;
    enc.pubKey[0] <== HX;
    enc.pubKey[1] <== HY;

    c1[0] <== enc.c1[0];
    c1[1] <== enc.c1[1];
    c2[0] <== enc.c2[0];
    c2[1] <== enc.c2[1];
}

component main = ElGamalFixedKey(40);
