// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

/// @title CircuitManifest
/// @notice Which proving key each deployed verifier belongs to.
///
/// @dev GENERATED by `circuits/scripts/gen_manifest.mjs`. Do not edit by hand -- a hand
///      edit makes this file agree with a verifier it was not derived from, which is
///      precisely the drift it exists to detect.
///
///      Each hash is sha256 over the canonical `<circuit>_vkey.json` emitted by
///      `snarkjs zkey export verificationkey`. It identifies the PROVING KEY, so it
///      changes whenever the trusted setup is re-run -- including after the ceremony.
///      That is intended: a post-ceremony deployment must not accept pre-ceremony
///      artifacts, and this is what makes that a compile-time fact rather than a
///      procedural one.
library CircuitManifest {
    /// @dev FixedKeyVerifier, 4 public signals.
    bytes32 internal constant PROBE_FIXED_KEY_VKEY = 0x54a796a2544ba65c2a11981b6a390edf2db7b8866c4c25a40e429fd77623c7bc;

    /// @dev PubKeyInputVerifier, 6 public signals.
    bytes32 internal constant PROBE_PUBKEY_INPUT_VKEY = 0x20ce891f4fb7e13230fd99103ff522d236c63833dea4cb806decda9b915aa73d;

    /// @dev DepositVerifier, 2 public signals.
    bytes32 internal constant DEPOSIT_VKEY = 0xacddde77a1b0b42ae95e9843d35a62b0fd071a66cd1b51a0b9fac7fd45f3a47c;

    /// @dev BetVerifier, 4 public signals.
    bytes32 internal constant BET_VKEY = 0x45fecd99ab84878e38709c0efb7189ec417e200ebe1e94eaa57132ce90ff04d9;

    /// @dev RedeemVerifier, 4 public signals.
    bytes32 internal constant REDEEM_VKEY = 0x92c3b82d65a3e892727795fd9a7bf07f2fb17e4ea9bc0e9b3c3d551a7c3c0ad4;

    /// @dev BetEncryptedVerifier, 8 public signals.
    bytes32 internal constant BET_ENCRYPTED_VKEY = 0x570cb7bf3368c777c0f8924dbf57d4013e01928563b5002757e6f158fbc8f895;

    /// @dev RedeemPrivateVerifier, 4 public signals.
    bytes32 internal constant REDEEM_PRIVATE_VKEY = 0xf8570229fd586507facfcb8f526c00c5be125be5d21e925c4b89391a0aa34ae8;

    /// @dev WithdrawVerifier, 4 public signals.
    bytes32 internal constant WITHDRAW_VKEY = 0x34a2335931874427da5c3cb5a05b1393f970fc8518bfc0426cd61573dd6dc891;

}
